name:                Euler499

dependencies:
- base >= 4.7 && < 5

executables:
  Euler499:
    main: Euler499.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    when:        
    - condition: false        
      other-modules: Paths_Euler495