name:                Euler495

dependencies:
- base >= 4.7 && < 5
- containers
- memoize
- poly
- vector

executables:
  Euler495-exe:
    main:                Euler495.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    when:        
    - condition: false        
      other-modules: Paths_Euler495